[build]
  publish = "dist"
  command = "npm ci && npm run build:frontend"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200